package uni.bugtracker.backend.model;

public enum Tag {
    NO_SUITABLE_TAG,
    BROKEN_LINK,
    SLOW_LOADING,
    BLANK_SCREEN,
    INTERFACE_ISSUE,
    FUNCTIONALITY_PROBLEMS,
    BROKEN_IMAGE,
    SEARCH_PROBLEM,
    FORM_NOT_WORKING,
    MOBILE_VIEW,
    REDIRECT_LOOP,
    LOGIN_ISSUE,
    REGISTER_ISSUE,
    FILTERS_NOT_WORKING,
    PAGINATION_ISSUE
}
